import { StyleSheet } from 'react-native';

export default StyleSheet.create({
	rowDivider: {
		height: 1,
		backgroundColor: '#EEF4FA',
		marginVertical: 6,
	},
	sectionBreak: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		marginVertical: 10,
	},
	sectionBreakLine: {
		flex: 1,
		height: 1,
		backgroundColor: '#EEF4FA',
	},
	sectionBreakLabel: {
		fontSize: 9,
		fontWeight: '700',
		color: '#8BA4BC',
		letterSpacing: 1.5,
	},
	row: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: 12,
		paddingVertical: 14,
		paddingHorizontal: 8,
		borderRadius: 12,
	},
	rowSelected: {
		backgroundColor: '#F3F8FD',
		paddingVertical: 18,
	},
	checkCircle: {
		width: 22,
		height: 22,
		borderRadius: 11,
		borderWidth: 1.5,
		borderColor: '#C8DFF0',
		alignItems: 'center',
		justifyContent: 'center',
		marginTop: 2,
	},
	checkCircleSelected: {
		backgroundColor: '#2A7AB6',
		borderColor: '#2A7AB6',
	},
	rowBody: {
		flex: 1,
		gap: 4,
	},
	codeRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 8,
	},
	codeTag: {
		backgroundColor: '#EBF4FC',
		borderRadius: 8,
		paddingHorizontal: 8,
		paddingVertical: 3,
	},
	codeText: {
		fontSize: 12,
		fontWeight: '700',
		color: '#2A7AB6',
	},
	codeRowRight: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
	},
	backBadge: {
		backgroundColor: '#EBF4FC',
		borderRadius: 5,
		paddingHorizontal: 5,
		paddingVertical: 1,
	},
	backBadgeText: {
		fontSize: 8,
		fontWeight: '700',
		color: '#2A7AB6',
		letterSpacing: 0.3,
	},
	unitsText: {
		fontSize: 11,
		color: '#8BA4BC',
		fontWeight: '600',
	},
	nameText: {
		fontSize: 13,
		fontWeight: '600',
		color: '#1A2A3A',
	},
	emptyState: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		paddingVertical: 10,
	},
	emptyText: {
		fontSize: 12,
		color: '#8BA4BC',
	},
	teacherPicker: {
		marginTop: 10,
		paddingTop: 10,
		borderTopWidth: 1,
		borderTopColor: '#EEF4FA',
		gap: 6,
	},
	teacherPickerLabel: {
		fontSize: 9,
		fontWeight: '700',
		color: '#8BA4BC',
		letterSpacing: 1.5,
		marginBottom: 4,
	},
	teacherOption: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
		padding: 10,
		borderRadius: 10,
		backgroundColor: '#F5F9FD',
		borderWidth: 1.5,
		borderColor: 'transparent',
	},
	teacherOptionChosen: {
		backgroundColor: '#EBF4FC',
		borderColor: '#2A7AB6',
	},
	teacherRadio: {
		width: 18,
		height: 18,
		borderRadius: 9,
		borderWidth: 1.5,
		borderColor: '#C8DFF0',
		alignItems: 'center',
		justifyContent: 'center',
		flexShrink: 0,
	},
	teacherRadioChosen: {
		borderColor: '#2A7AB6',
	},
	teacherRadioDot: {
		width: 8,
		height: 8,
		borderRadius: 4,
		backgroundColor: '#2A7AB6',
	},
	teacherNameCol: {
		flex: 1,
		gap: 3,
	},
	teacherName: {
		fontSize: 13,
		fontWeight: '600',
		color: '#1A2A3A',
	},
	teacherDeptBadge: {
		alignSelf: 'flex-start',
		backgroundColor: '#EBF4FC',
		borderRadius: 5,
		paddingHorizontal: 5,
		paddingVertical: 1,
	},
	teacherDeptText: {
		fontSize: 9,
		fontWeight: '700',
		color: '#2A7AB6',
		letterSpacing: 0.3,
	},
	teacherNoSchedule: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 6,
		paddingVertical: 6,
	},
	teacherNoScheduleText: {
		fontSize: 11,
		color: '#8BA4BC',
		flex: 1,
	},
});
