import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  card: {
    marginHorizontal: 16,
    marginBottom: 14,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#1A2A3A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.09,
    shadowRadius: 8,
  },
  banner: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    minHeight: 106,
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  bgIcon: {
    position: 'absolute',
    right: 14,
    bottom: 10,
  },
  bannerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  subjectCode: {
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.8)',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  subjectTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
    lineHeight: 22,
    paddingRight: 60,
  },
  body: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  unitChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EBF4FC',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  unitText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#2A7AB6',
  },
  teacherText: {
    fontSize: 12,
    color: '#5A7A9A',
    flex: 1,
    textAlign: 'right',
    marginLeft: 10,
  },
  gradeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#EBF4FC',
  },
  gradeLabel: {
    fontSize: 12,
    color: '#8BA4BC',
    fontWeight: '500',
  },
  gradeValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1a3c5e',
  },
  gradeValuePending: {
    fontSize: 18,
    color: '#8BA4BC',
    fontWeight: '600',
  },
});
