import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  card: {
    marginHorizontal: 10,
    marginBottom: 8,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#1A2A3A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.09,
    shadowRadius: 8,
  },
  banner: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 10,
    minHeight: 78,
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  bgIcon: {
    position: 'absolute',
    right: 10,
    bottom: 6,
  },
  bannerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  subjectCode: {
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.8)',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  subjectTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
    lineHeight: 20,
    paddingRight: 50,
  },
  body: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    gap: 6,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  unitChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EBF4FC',
    borderRadius: 7,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  unitText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#2A7AB6',
  },
  teacherText: {
    fontSize: 11,
    color: '#5A7A9A',
    flex: 1,
    textAlign: 'right',
    marginLeft: 8,
  },
  gradeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#EBF4FC',
  },
  gradeLabel: {
    fontSize: 11,
    color: '#8BA4BC',
    fontWeight: '500',
  },
  gradeValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1a3c5e',
  },
  gradeValuePending: {
    fontSize: 15,
    color: '#8BA4BC',
    fontWeight: '600',
  },
});
