import { StyleSheet } from 'react-native';

export default StyleSheet.create({
	safe: { flex: 1, backgroundColor: '#1a3c5e' },
	header: {
		backgroundColor: '#1a3c5e',
		paddingHorizontal: 18,
		paddingTop: 10,
		paddingBottom: 16,
	},
	headerRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
	},
	backButton: {
		width: 36,
		height: 36,
		borderRadius: 18,
		backgroundColor: 'rgba(255,255,255,0.16)',
		alignItems: 'center',
		justifyContent: 'center',
	},
	headerTitle: {
		fontSize: 18,
		fontWeight: '800',
		color: '#FFFFFF',
		letterSpacing: 0.2,
	},
	headerSubtitle: {
		fontSize: 12,
		color: 'rgba(255,255,255,0.6)',
		marginTop: 4,
	},
	content: { flex: 1, backgroundColor: '#F2F6FA' },
	tipCard: {
		flexDirection: 'row',
		gap: 10,
		backgroundColor: '#EBF4FC',
		borderRadius: 14,
		padding: 12,
		marginHorizontal: 16,
		marginTop: 12,
	},
	tipText: {
		flex: 1,
		fontSize: 12,
		color: '#2A7AB6',
		lineHeight: 17,
	},
	statusCard: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
		backgroundColor: '#FFFFFF',
		borderRadius: 12,
		padding: 12,
		marginHorizontal: 16,
		marginTop: 10,
		borderWidth: 1,
		borderColor: '#E2EDF7',
	},
	statusText: {
		flex: 1,
		fontSize: 12,
		color: '#1A2A3A',
		lineHeight: 17,
	},
	statusMeta: {
		fontSize: 11,
		color: '#8BA4BC',
		marginTop: 4,
	},
	webWrap: {
		flex: 1,
		marginHorizontal: 16,
		marginTop: 12,
		marginBottom: 16,
		borderRadius: 16,
		overflow: 'hidden',
		backgroundColor: '#FFFFFF',
		shadowColor: '#1a3c5e',
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 0.08,
		shadowRadius: 10,
		elevation: 3,
	},
	webView: { flex: 1, backgroundColor: '#FFFFFF' },
	actionWrap: {
		position: 'absolute',
		right: 14,
		bottom: 14,
	},
	scanButton: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		backgroundColor: '#2A7AB6',
		borderRadius: 18,
		paddingHorizontal: 16,
		paddingVertical: 12,
		shadowColor: '#1a3c5e',
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 0.18,
		shadowRadius: 6,
		elevation: 4,
	},
	scanButtonDisabled: {
		backgroundColor: '#C8DFF0',
	},
	scanText: {
		fontSize: 13,
		fontWeight: '700',
		color: '#FFFFFF',
	},
	scanTextDisabled: {
		color: '#8BA4BC',
	},
});
